# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: performancestats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='performancestats.proto',
  package='carwatchdog',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16performancestats.proto\x12\x0b\x63\x61rwatchdog\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"K\n\tTimeOfDay\x12\r\n\x05hours\x18\x01 \x01(\x05\x12\x0f\n\x07minutes\x18\x02 \x01(\x05\x12\x0f\n\x07seconds\x18\x03 \x01(\x05\x12\r\n\x05nanos\x18\x04 \x01(\x05\"Y\n\x0fProcessCpuStats\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0b\x63pu_time_ms\x18\x02 \x01(\x05\x12 \n\x18package_cpu_time_percent\x18\x03 \x01(\x02\"\xa6\x01\n\x0fPackageCpuStats\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63pu_time_ms\x18\x03 \x01(\x05\x12\x1e\n\x16total_cpu_time_percent\x18\x04 \x01(\x02\x12\x37\n\x11process_cpu_stats\x18\x05 \x03(\x0b\x32\x1c.carwatchdog.ProcessCpuStats\"\xa3\x02\n\x0fStatsCollection\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1f\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x11.carwatchdog.Date\x12$\n\x04time\x18\x03 \x01(\x0b\x32\x16.carwatchdog.TimeOfDay\x12\x19\n\x11total_cpu_time_ms\x18\x04 \x01(\x05\x12\x18\n\x10idle_cpu_time_ms\x18\x05 \x01(\x05\x12\x17\n\x0fio_wait_time_ms\x18\x06 \x01(\x05\x12\x18\n\x10\x63ontext_switches\x18\x07 \x01(\x03\x12\x1c\n\x14io_blocked_processes\x18\x08 \x01(\x05\x12\x37\n\x11package_cpu_stats\x18\t \x03(\x0b\x32\x1c.carwatchdog.PackageCpuStats\"E\n\x10SystemEventStats\x12\x31\n\x0b\x63ollections\x18\x01 \x03(\x0b\x32\x1c.carwatchdog.StatsCollection\"\x84\x01\n\x10PerformanceStats\x12\x36\n\x0f\x62oot_time_stats\x18\x01 \x01(\x0b\x32\x1d.carwatchdog.SystemEventStats\x12\x38\n\x11user_switch_stats\x18\x02 \x03(\x0b\x32\x1d.carwatchdog.SystemEventStats')
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='carwatchdog.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='carwatchdog.Date.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='carwatchdog.Date.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='carwatchdog.Date.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=87,
)


_TIMEOFDAY = _descriptor.Descriptor(
  name='TimeOfDay',
  full_name='carwatchdog.TimeOfDay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hours', full_name='carwatchdog.TimeOfDay.hours', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minutes', full_name='carwatchdog.TimeOfDay.minutes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='carwatchdog.TimeOfDay.seconds', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nanos', full_name='carwatchdog.TimeOfDay.nanos', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=164,
)


_PROCESSCPUSTATS = _descriptor.Descriptor(
  name='ProcessCpuStats',
  full_name='carwatchdog.ProcessCpuStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='carwatchdog.ProcessCpuStats.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_time_ms', full_name='carwatchdog.ProcessCpuStats.cpu_time_ms', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_cpu_time_percent', full_name='carwatchdog.ProcessCpuStats.package_cpu_time_percent', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=255,
)


_PACKAGECPUSTATS = _descriptor.Descriptor(
  name='PackageCpuStats',
  full_name='carwatchdog.PackageCpuStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='carwatchdog.PackageCpuStats.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_name', full_name='carwatchdog.PackageCpuStats.package_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_time_ms', full_name='carwatchdog.PackageCpuStats.cpu_time_ms', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_cpu_time_percent', full_name='carwatchdog.PackageCpuStats.total_cpu_time_percent', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_cpu_stats', full_name='carwatchdog.PackageCpuStats.process_cpu_stats', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=424,
)


_STATSCOLLECTION = _descriptor.Descriptor(
  name='StatsCollection',
  full_name='carwatchdog.StatsCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='carwatchdog.StatsCollection.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='carwatchdog.StatsCollection.date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='carwatchdog.StatsCollection.time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_cpu_time_ms', full_name='carwatchdog.StatsCollection.total_cpu_time_ms', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idle_cpu_time_ms', full_name='carwatchdog.StatsCollection.idle_cpu_time_ms', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='io_wait_time_ms', full_name='carwatchdog.StatsCollection.io_wait_time_ms', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='context_switches', full_name='carwatchdog.StatsCollection.context_switches', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='io_blocked_processes', full_name='carwatchdog.StatsCollection.io_blocked_processes', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_cpu_stats', full_name='carwatchdog.StatsCollection.package_cpu_stats', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=718,
)


_SYSTEMEVENTSTATS = _descriptor.Descriptor(
  name='SystemEventStats',
  full_name='carwatchdog.SystemEventStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collections', full_name='carwatchdog.SystemEventStats.collections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=720,
  serialized_end=789,
)


_PERFORMANCESTATS = _descriptor.Descriptor(
  name='PerformanceStats',
  full_name='carwatchdog.PerformanceStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boot_time_stats', full_name='carwatchdog.PerformanceStats.boot_time_stats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_switch_stats', full_name='carwatchdog.PerformanceStats.user_switch_stats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=792,
  serialized_end=924,
)

_PACKAGECPUSTATS.fields_by_name['process_cpu_stats'].message_type = _PROCESSCPUSTATS
_STATSCOLLECTION.fields_by_name['date'].message_type = _DATE
_STATSCOLLECTION.fields_by_name['time'].message_type = _TIMEOFDAY
_STATSCOLLECTION.fields_by_name['package_cpu_stats'].message_type = _PACKAGECPUSTATS
_SYSTEMEVENTSTATS.fields_by_name['collections'].message_type = _STATSCOLLECTION
_PERFORMANCESTATS.fields_by_name['boot_time_stats'].message_type = _SYSTEMEVENTSTATS
_PERFORMANCESTATS.fields_by_name['user_switch_stats'].message_type = _SYSTEMEVENTSTATS
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['TimeOfDay'] = _TIMEOFDAY
DESCRIPTOR.message_types_by_name['ProcessCpuStats'] = _PROCESSCPUSTATS
DESCRIPTOR.message_types_by_name['PackageCpuStats'] = _PACKAGECPUSTATS
DESCRIPTOR.message_types_by_name['StatsCollection'] = _STATSCOLLECTION
DESCRIPTOR.message_types_by_name['SystemEventStats'] = _SYSTEMEVENTSTATS
DESCRIPTOR.message_types_by_name['PerformanceStats'] = _PERFORMANCESTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.Date)
  })
_sym_db.RegisterMessage(Date)

TimeOfDay = _reflection.GeneratedProtocolMessageType('TimeOfDay', (_message.Message,), {
  'DESCRIPTOR' : _TIMEOFDAY,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.TimeOfDay)
  })
_sym_db.RegisterMessage(TimeOfDay)

ProcessCpuStats = _reflection.GeneratedProtocolMessageType('ProcessCpuStats', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSCPUSTATS,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.ProcessCpuStats)
  })
_sym_db.RegisterMessage(ProcessCpuStats)

PackageCpuStats = _reflection.GeneratedProtocolMessageType('PackageCpuStats', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGECPUSTATS,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.PackageCpuStats)
  })
_sym_db.RegisterMessage(PackageCpuStats)

StatsCollection = _reflection.GeneratedProtocolMessageType('StatsCollection', (_message.Message,), {
  'DESCRIPTOR' : _STATSCOLLECTION,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.StatsCollection)
  })
_sym_db.RegisterMessage(StatsCollection)

SystemEventStats = _reflection.GeneratedProtocolMessageType('SystemEventStats', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMEVENTSTATS,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.SystemEventStats)
  })
_sym_db.RegisterMessage(SystemEventStats)

PerformanceStats = _reflection.GeneratedProtocolMessageType('PerformanceStats', (_message.Message,), {
  'DESCRIPTOR' : _PERFORMANCESTATS,
  '__module__' : 'performancestats_pb2'
  # @@protoc_insertion_point(class_scope:carwatchdog.PerformanceStats)
  })
_sym_db.RegisterMessage(PerformanceStats)


# @@protoc_insertion_point(module_scope)
