# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# DO NOT EDIT MANUALLY
# This file was autogenerated by vhal_const_generate.py
from vhal_consts_2_0 import *

# VehicleProperty
VEHICLE_PROPERTY_WHEEL_TICK = 291570438
VEHICLE_PROPERTY_OBD2_LIVE_FRAME = 299896064
VEHICLE_PROPERTY_OBD2_FREEZE_FRAME = 299896065
VEHICLE_PROPERTY_OBD2_FREEZE_FRAME_INFO = 299896066
VEHICLE_PROPERTY_OBD2_FREEZE_FRAME_CLEAR = 299896067
VEHICLE_PROPERTY_VEHICLE_MAP_SERVICE = 299895808
