#!/usr/bin/env python3.4
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This script generates vhal_consts_x_y.py files for use in vhal_emulator
# They are generated from corresponding data in Vehicle HAL types.hal files
# To run, invoke at a shell by saying:
# $ packages/services/Car/tools/emulator/vhal_const_generate.py
# The script will automatically locate itself and the required HAL files and will write next
# to itself vhal_consts_x.y.py for any version of Vehicle HAL that it knows about
# Those files can then be used with vhal_emulator.py as per that script's documentation

import datetime

def printHeader(dest):
    year = datetime.datetime.now().year
    print("# Copyright (C) %s The Android Open Source Project" % year, file=dest)
    print("#", file=dest)
    print("# Licensed under the Apache License, Version 2.0 (the \"License\");", file=dest)
    print("# you may not use this file except in compliance with the License.", file=dest)
    print("# You may obtain a copy of the License at", file=dest)
    print("#", file=dest)
    print("#      http://www.apache.org/licenses/LICENSE-2.0", file=dest)
    print("#", file=dest)
    print("# Unless required by applicable law or agreed to in writing, software", file=dest)
    print("# distributed under the License is distributed on an \"AS IS\" BASIS,", file=dest)
    print("# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.", file=dest)
    print("# See the License for the specific language governing permissions and", file=dest)
    print("# limitations under the License.", file=dest)
    print("#", file=dest)
    print("# DO NOT EDIT MANUALLY", file=dest)
    print("# This file was autogenerated by vhal_const_generate.py", file=dest)

def printEnum(doc, name, prefix, dest, postprocess=lambda x: x):
    enum_object = doc['enums'][name]
    print("\n# %s" % name, file=dest)
    for case in enum_object.cases:
        print('%s%s = %s' % (prefix, case.name,
            postprocess(case.value.resolve(enum_object, doc))),
            file=dest)

import os, os.path
import sys

script_directory = os.path.join(os.path.dirname(os.path.abspath(__file__)))
parent_location = os.path.abspath(os.path.join(script_directory, '..'))
sys.path.append(parent_location)

from hidl_parser import parser

android_build_top = os.environ.get("ANDROID_BUILD_TOP", None)
if android_build_top is not None:
    vhal_location = os.path.join(android_build_top, 'hardware','interfaces','automotive','vehicle')
else:
    vhal_location = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
        '..','..','..','..','..','hardware','interfaces','automotive','vehicle'
    ))
if not(os.path.exists(vhal_location) and os.path.isdir(vhal_location)):
    print("Vehicle HAL was not found at %s. lunch may provide a correct environment, or files moved" % vhal_location)
    sys.exit(1)

vhal_20_file = os.path.join(vhal_location, '2.0', 'types.hal')
vhal_21_file = os.path.join(vhal_location, '2.1', 'types.hal')

print("Generating content from Vehicle HAL 2.0 (%s) and 2.1 (%s)" % (vhal_20_file, vhal_21_file))

vhal_20_doc = parser.parse(vhal_20_file)
vhal_21_doc = parser.parse(vhal_21_file)
vhal_21_doc['enums']['VehiclePropertyGroup'] = vhal_20_doc['enums']['VehiclePropertyGroup']
vhal_21_doc['enums']['VehiclePropertyType'] = vhal_20_doc['enums']['VehiclePropertyType']
vhal_21_doc['enums']['VehicleArea'] = vhal_20_doc['enums']['VehicleArea']

def generateHal20():
    vhal_20_file = open(os.path.join(script_directory, 'vhal_consts_2_0.py'), 'w')

    printHeader(vhal_20_file)
    printEnum(vhal_20_doc, 'VehicleProperty', 'VEHICLE_PROPERTY_', vhal_20_file)
    printEnum(vhal_20_doc, 'VehiclePropertyType', 'VEHICLE_VALUE_TYPE_', vhal_20_file, lambda x : hex(x))
    printEnum(vhal_20_doc, 'VehicleAreaZone', 'VEHICLE_ZONE_', vhal_20_file, lambda x : hex(x))

    print("\n# Create a container of value_type constants to be used by vhal_emulator", file=vhal_20_file)
    print("class vhal_types_2_0:", file=vhal_20_file)
    print("    TYPE_STRING =  [VEHICLE_VALUE_TYPE_STRING]", file=vhal_20_file)
    print("    TYPE_BYTES  =  [VEHICLE_VALUE_TYPE_BYTES]", file=vhal_20_file)
    print("    TYPE_INT32  =  [VEHICLE_VALUE_TYPE_BOOLEAN,", file=vhal_20_file)
    print("                    VEHICLE_VALUE_TYPE_INT32]", file=vhal_20_file)
    print("    TYPE_INT64  =  [VEHICLE_VALUE_TYPE_INT64]", file=vhal_20_file)
    print("    TYPE_FLOAT  =  [VEHICLE_VALUE_TYPE_FLOAT]", file=vhal_20_file)
    print("    TYPE_INT32S =  [VEHICLE_VALUE_TYPE_INT32_VEC]", file=vhal_20_file)
    print("    TYPE_FLOATS =  [VEHICLE_VALUE_TYPE_FLOAT_VEC]", file=vhal_20_file)
    print("    TYPE_COMPLEX = [VEHICLE_VALUE_TYPE_COMPLEX]", file=vhal_20_file)

def generateHal21():
    vhal_21_file = open(os.path.join(script_directory, 'vhal_consts_2_1.py'), 'w')
    printHeader(vhal_21_file)
    print('from vhal_consts_2_0 import *', file=vhal_21_file)
    printEnum(vhal_21_doc, 'VehicleProperty', 'VEHICLE_PROPERTY_', vhal_21_file)

generateHal20()
generateHal21()
