load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "5fa3c738d33acca3b97622a13a741129f67ef43f5fdfcec63b29374cc0574c29",
    strip_prefix = "rules_python-0.9.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.9.0.tar.gz",
)

http_archive(
    name = "gtest",
    strip_prefix = "googletest-15460959cbbfa20e66ef0b5ab497367e47fc0a04",
    url = "https://github.com/google/googletest/archive/15460959cbbfa20e66ef0b5ab497367e47fc0a04.zip",
)

LUA_SRC = "../../../../../../external/lua/src"

new_local_repository(
    name = "lua",
    build_file = "lua.BUILD",
    path = LUA_SRC,
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    name = "dependencies",
    requirements = "//:requirements.txt",
)
